spring:
  application:
    name: cowmjucraft

  profiles:
    default: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL:}
    username: ${SPRING_DATASOURCE_USERNAME:}
    password: ${SPRING_DATASOURCE_PASSWORD:}

  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

server:
  port: 8080

admin:
  user-id: ${ADMIN_USER_ID:}
  password: ${ADMIN_PASSWORD:}

jwt:
  secret: ${JWT_SECRET:}
  expiration-seconds: ${JWT_EXPIRATION_SECONDS:3600}